r4[image]="pietrospadaccino/frr"
r5[image]="pietrospadaccino/frr"

# AS 100
pc1[0]=A
r1[0]=A
r1[1]=B
r2[0]=B
r1[2]=C
r4[0]=C
r1[3]=D
r3[0]=D
r2[1]=E
r4[1]=E
r3[1]=F
r4[2]=F

# Link AS 100 <--> AS 200
r4[3]=G
r5[0]=G

# AS 200
r5[1]=H
r8[0]=H
r8[1]=M
r7[0]=M
r7[1]=L
r6[0]=L
r6[1]=K
r5[2]=K
r5[3]=J
r7[2]=J
r8[2]=I
r6[2]=I
r6[3]=P
s1[0]=P

# Link AS 200 <--> Network 3
r7[3]=N
r9[0]=N

#Network 3
r9[1]=O
s2[0]=O
pc2[0]=O


