
port 7000


proto tcp

dev tun

ca /root/ca.crt
cert /root/vpn_server.crt
key /root/vpn_server.key  


dh /root/dh2048.pem


topology subnet


server 10.0.0.0 255.255.255.0

push "route 10.0.0.0 255.255.255.0"


client-config-dir /root/ccd

client-to-client


keepalive 10 120


persist-key
persist-tun

verb 3

